apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pod
  namespace: default
spec:
  type: oci
  interval: 1m0s
  url: oci://gollistest.azurecr.io/helm/hello-world
 ---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    repository: oci://gollistest.azurecr.io/helm/hello-world
    name: podinfo
