apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pod
  namespace: default
spec:
  type: oci
  interval: 1m0s
  url: oci://gollistest.azurecr.io/helm/hello-world