apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gollis-release
  namespace: flux
spec:
  interval: 5m
  chart:
    spec:
      chart: hello-world
      sourceRef:
        kind: HelmRepository
        name: gollis-acr
        namespace: flux
      interval: 1m
